### PR TITLE
bit of cleanup and prevention of loading same resource in ContentStor…

### PR DESCRIPTION
**Pull request by caveguy427**
…e more than once
i do not exactly know what im doing

### CODE REVIEW

**Comment by EpicTofuu** [comment]
this looks really good!

the only primary concern I have is with the way you're checking file paths for duplicates.
I'm sure it works, the only issue is that I was intending on adding an extra string in `IResource` to store the path. Then every time `LoadResource()` is called, it would search the values in the `resources` dictionary for duplicate paths.

Doing it this way allows us to expose the file path to other parts of the code which can be helpful later and makes better use of the `IResource` interface as a means of storing data. If you don't feel like changing your PR to do that, that's fine.

I'll review this PR in depth later.

**Comment by caveguy427** [comment]
i apologize for im not experienced (pretty clear by how i closed a pull request only because of a conflict on my fork)
if we would store the path in `IResource` as a property, wouldnt each derived class need to do this?
`
    public interface IResource : IDisposable
    {
        IntPtr Handle { get; }
        // actually i do not know if `Path` should be either:
        // - set in `ContentCache.LoadResource`
        // - set in the constructor of all derived classes
        string Path { get; set; }
    }
    
    public class AResource
    {
        // ...
        // im talking about doing this
        public string Path { get; set; }
        // ...
    }
`
personally i think its redundant, but like i said im not experienced

**Comment by EpicTofuu** [comment]
That's a good point. I've given it some thought and I think the best way to do things would be to 
- make `IResource` an abstract class (and rename it `Resource`)
- keep `Path` as a field with no set.

this fixes the issue of having to implement a path string for every resource

The primary reason for storing the path in the resource being resource unloading. When the resource is unloaded, removing the `Resource` from the dictionary also removes the path which allows for the same resource to be loaded in again later. Storing paths in a separate list makes it harder to find the right path to remove when a resource is removed (especially when resources can be given custom keys in the dictionary).

**Comment by caveguy427** [comment]
sure, ill try that
however i do not know how would `Resource.Path` be set in the first place, if it cannot be publicly set
would it be alright if the `path` argument to an `ILoader.GetResource` be also passed down to the constructor of any deriving `Resource`s?
like this:
```cs
    public abstract class Resource : IDisposable
    {
        public IntPtr Handle { get; }
        public string Path { get; protected set; }
        
        public Resource(string path) => Path = path;
    }
    
    public class RandomResource : Resource
    {
        // ...
        public RandomResource(string path) : base(path)
        { }
        // ...
    }
    
    public class RandomLoader : ILoader
    {
        // ...
        public Resource GetResource(Game game, string path, ILoadArgs args)
        {
            var final = new RandomResource(path);
            return final;
        }
        // ...
    }
```

**Comment by EpicTofuu** [comment]
I'd say it's best to have two constructors, one that takes an IntPtr with the path and one with just the IntPtr. Currently I'm already creating a texture without a path so the pathless constructor already has a use case.

**Comment by caveguy427** [comment]
ive attempted to do what has been suggested, anything i should change?

**Review by EpicTofuu — APPROVED** [review]
perfect. I'll merge these straight away! 
thanks for you help.

**Pull request merged**
